name: mpi-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - scipy
  - statsmodels
  - plotly
  - requests
  - python-dotenv
  - streamlit
  - openpyxl
  - altair
